"""Data models for the TODO application.

This module defines the Task dataclass representing a single todo item
with SQLite persistence support, plus Project and TaskStats dataclasses
for Phase 2 features.
"""

import sqlite3
from dataclasses import dataclass
from datetime import date, datetime


@dataclass
class Task:
    """Represents a single todo task.

    Attributes:
        id: Unique identifier (auto-generated by database)
        title: Short description of what needs to be done
        description: Optional longer description with details
        status: Current state - either "pending" or "done"
        created_at: When the task was first created
        updated_at: When the task was last modified
        due_date: Optional due date for the task
        project_id: Optional foreign key to projects table
    """

    id: int
    title: str
    description: str
    status: str  # Literal["pending", "done"]
    created_at: datetime
    updated_at: datetime
    due_date: date | None = None
    project_id: int | None = None

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "Task":
        """Create a Task from a database row.

        Args:
            row: SQLite Row object with task data.

        Returns:
            Task instance populated with row data.

        Example:
            >>> row = cursor.fetchone()
            >>> task = Task.from_row(row)
        """
        # Handle optional due_date column
        due_date_val = row["due_date"] if "due_date" in row.keys() else None
        parsed_due_date = None
        if due_date_val:
            parsed_due_date = date.fromisoformat(due_date_val)

        # Handle optional project_id column
        project_id_val = row["project_id"] if "project_id" in row.keys() else None

        return cls(
            id=row["id"],
            title=row["title"],
            description=row["description"],
            status=row["status"],
            created_at=datetime.fromisoformat(row["created_at"]),
            updated_at=datetime.fromisoformat(row["updated_at"]),
            due_date=parsed_due_date,
            project_id=project_id_val,
        )

    def is_completed(self) -> bool:
        """Check if task is marked as done.

        Returns:
            True if status is "done", False otherwise.

        Example:
            >>> task.status = "done"
            >>> task.is_completed()
            True
        """
        return self.status == "done"

    def format_status(self) -> str:
        """Format status for display.

        Returns:
            "[ ] Pending" for pending tasks, "[x] Done" for completed tasks.

        Example:
            >>> task.status = "pending"
            >>> task.format_status()
            "[ ] Pending"
        """
        if self.status == "done":
            return "[x] Done"
        return "[ ] Pending"

    def format_date(self) -> str:
        """Format created_at timestamp for display.

        Returns:
            Formatted date string in "YYYY-MM-DD HH:MM" format.

        Example:
            >>> task.created_at = datetime(2025, 12, 4, 10, 15)
            >>> task.format_date()
            "2025-12-04 10:15"
        """
        return self.created_at.strftime("%Y-%m-%d %H:%M")

    def format_due_date(self) -> str:
        """Format due_date for display.

        Returns:
            Formatted date string in "YYYY-MM-DD" format, or empty string if None.

        Example:
            >>> task.due_date = date(2025, 12, 25)
            >>> task.format_due_date()
            "2025-12-25"
        """
        if self.due_date is None:
            return ""
        return self.due_date.isoformat()


@dataclass
class Project:
    """A project/category for grouping tasks.

    Attributes:
        id: Unique identifier (auto-generated by database)
        name: Unique project name (case-insensitive)
        description: Optional project description
        created_at: When the project was created
    """

    id: int
    name: str
    description: str
    created_at: datetime
    _task_count: int = 0

    @property
    def task_count(self) -> int:
        """Number of tasks in this project (populated by query)."""
        return self._task_count

    @task_count.setter
    def task_count(self, value: int) -> None:
        self._task_count = value

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "Project":
        """Create a Project from a database row.

        Args:
            row: SQLite Row object with project data.

        Returns:
            Project instance populated with row data.
        """
        project = cls(
            id=row["id"],
            name=row["name"],
            description=row["description"] or "",
            created_at=datetime.fromisoformat(row["created_at"]),
        )
        # Handle optional task_count from JOIN query
        if "task_count" in row.keys():
            project.task_count = row["task_count"] or 0
        return project

    def format_date(self) -> str:
        """Format created_at timestamp for display.

        Returns:
            Formatted date string in "YYYY-MM-DD HH:MM" format.
        """
        return self.created_at.strftime("%Y-%m-%d %H:%M")


@dataclass
class TaskStats:
    """Statistics about tasks.

    Attributes:
        total: Total number of tasks
        pending: Number of pending tasks
        completed: Number of completed tasks
        due_today: Number of tasks due today
        overdue: Number of overdue pending tasks
    """

    total: int
    pending: int
    completed: int
    due_today: int
    overdue: int

    @property
    def completion_rate(self) -> float:
        """Completion rate as percentage (0-100).

        Returns:
            Percentage of completed tasks, or 0.0 if no tasks exist.
        """
        if self.total == 0:
            return 0.0
        return (self.completed / self.total) * 100
