"""Data models for the TODO application.

This module defines the Task dataclass representing a single todo item
with SQLite persistence support.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Task:
    """Represents a single todo task.

    Attributes:
        id: Unique identifier (auto-generated by database)
        title: Short description of what needs to be done
        description: Optional longer description with details
        status: Current state - either "pending" or "done"
        created_at: When the task was first created
        updated_at: When the task was last modified
    """

    id: int
    title: str
    description: str
    status: str  # Literal["pending", "done"]
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "Task":
        """Create a Task from a database row.

        Args:
            row: SQLite Row object with task data.

        Returns:
            Task instance populated with row data.

        Example:
            >>> row = cursor.fetchone()
            >>> task = Task.from_row(row)
        """
        return cls(
            id=row["id"],
            title=row["title"],
            description=row["description"],
            status=row["status"],
            created_at=datetime.fromisoformat(row["created_at"]),
            updated_at=datetime.fromisoformat(row["updated_at"]),
        )

    def is_completed(self) -> bool:
        """Check if task is marked as done.

        Returns:
            True if status is "done", False otherwise.

        Example:
            >>> task.status = "done"
            >>> task.is_completed()
            True
        """
        return self.status == "done"

    def format_status(self) -> str:
        """Format status for display.

        Returns:
            "[ ] Pending" for pending tasks, "[x] Done" for completed tasks.

        Example:
            >>> task.status = "pending"
            >>> task.format_status()
            "[ ] Pending"
        """
        if self.status == "done":
            return "[x] Done"
        return "[ ] Pending"

    def format_date(self) -> str:
        """Format created_at timestamp for display.

        Returns:
            Formatted date string in "YYYY-MM-DD HH:MM" format.

        Example:
            >>> task.created_at = datetime(2025, 12, 4, 10, 15)
            >>> task.format_date()
            "2025-12-04 10:15"
        """
        return self.created_at.strftime("%Y-%m-%d %H:%M")
